name: CI/CD Workflow
on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.ref == 'refs/heads/develop' && 'DEV' || github.ref == 'refs/heads/master' && 'PROD' || 'OTHER' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.x

      - name: Build .NET Core App
        run: |
          dotnet restore
          dotnet build

      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4.10

      - name: Set environment-specific secrets
        run: |
          if [ "${{ env.ENVIRONMENT }}" == "DEV" ]; then
            export OPENSHIFT_SERVER="${{ secrets.OPENSHIFT_SERVER_DEVELOPMENT }}"
            export OPENSHIFT_TOKEN="${{ secrets.OPENSHIFT_TOKEN_DEVELOPMENT }}"
            export OPENSHIFT_NAMESPACE="${{ secrets.OPENSHIFT_NAMESPACE_DEVELOPMENT }}"
          elif [ "${{ env.ENVIRONMENT }}" == "PROD" ]; then
            export OPENSHIFT_SERVER="${{ secrets.OPENSHIFT_SERVER_PRODUCTION }}"
            export OPENSHIFT_TOKEN="${{ secrets.OPENSHIFT_TOKEN_PRODUCTION }}"
            export OPENSHIFT_NAMESPACE="${{ secrets.OPENSHIFT_NAMESPACE_PRODUCTION }}"
          fi

      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
          openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}

      - name: Start OpenShift Build
        run: |
          oc start-build bc/service-billing --wait
